# Generated by Django 3.0.5 on 2021-04-16 23:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100, unique=True)),
                ('e_mail', models.EmailField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi byc wprowadzony w formacie +XX XXX XXX XXX', regex='^\\+?1?\\d{11}$')])),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
