# Generated by Django 3.0.5 on 2021-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=4),
            preserve_default=False,
        ),
    ]
