# Generated by Django 3.0.5 on 2021-04-30 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedrecipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addedrecipe',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
