# Generated by Django 3.0.5 on 2021-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='ingridients',
            field=models.ManyToManyField(to='recipes.Recipe'),
        ),
    ]
