# Generated by Django 3.0.5 on 2021-04-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210427_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedrecipe',
            name='quantity',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
