# Generated by Django 3.0.5 on 2021-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210503_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
