# Generated by Django 3.0.5 on 2021-04-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210427_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedrecipe',
            name='quantity',
        ),
    ]
