export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_FAVOURITES_START = "FETCH_FAVOURITES_START";
export const FETCH_FAVOURITES_SUCCESS = "FETCH_FAVOURITES_SUCCESS";
export const FETCH_FAVOURITES_FAIL = "FETCH_FAVOURITES_FAIL";

export const FETCH_SHOPPING_LIST_START = "FETCH_SHOPPING_LIST_START";
export const FETCH_SHOPPING_LIST_SUCCESS = "FETCH_SHOPPING_LIST_SUCCESS";
export const FETCH_SHOPPING_LIST_FAIL = "FETCH_SHOPPING_LIST_FAIL";
